### ISSUE TITLE
Log what error caused a rollback in query engine

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-engines#879]
While investigating this error https://github.com/prisma/prisma/issues/2921 we noted that the error logs from Prisma client log a ROLLBACK query but there is no reason about why the query engine had to rollback. 

Being able to see that would be super helpful in debugging.

**Comment by janpio** [comment]
This needs an example of the output that is currently being generated for a `ROLLBACK` so it becomes clear, what information is currently missing.

**Comment by divyenduz** [comment]
I tried the reproduction from https://github.com/prisma/prisma/issues/2921 to get the relevant logs but the full log with DEBUG=* do not have any rollback statements (reproduction works). 

I will close this issue for now and re-open when I run into this again with an example. I already tried a couple of approaches to force the QE to do a rollback but to no avail. 

Full logs for reference: 

```
2020-07-31T13:46:58.668Z prisma-client {
  engineConfig: {
    cwd: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921',
    debug: false,
    datamodelPath: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client',
      binaryTargets: [],
      experimentalFeatures: [],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: true,
    flags: [],
    clientVersion: '2.2.0-dev.36',
    enableExperimental: []
  }
}
2020-07-31T13:46:58.673Z prisma-client Prisma Client call:
2020-07-31T13:46:58.673Z prisma-client prisma.work.findMany(undefined)
2020-07-31T13:46:58.673Z prisma-client Generated request:
2020-07-31T13:46:58.673Z prisma-client query {
  findManyWork {
    id
    userId
    workType
  }
}

2020-07-31T13:46:58.674Z engine { cwd: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921' }
2020-07-31T13:46:58.675Z engine {
  dotPrismaPath: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/.prisma/client/query-engine-darwin'
}
2020-07-31T13:46:58.676Z plusX Execution permissions of /Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/.prisma/client/query-engine-darwin are fine
2020-07-31T13:46:58.676Z engine { flags: [ '--enable-raw-queries' ] }
2020-07-31T13:46:58.677Z engine port: 60180
2020-07-31T13:46:58.695Z engine stdout {
  timestamp: 'Jul 31 19:16:58.694',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a postgresql pool with up to 13 connections.' }
}
2020-07-31T13:46:58.699Z engine stdout {
  timestamp: 'Jul 31 19:16:58.699',
  level: 'INFO',
  target: 'query_engine::server',
  fields: { message: 'Started http server on 127.0.0.1:60180' }
}
2020-07-31T13:46:58.701Z prisma-client Client Version 2.2.0-dev.36
2020-07-31T13:46:58.701Z prisma-client Engine Version a0b56e4a4bc0dc6216e1cb26bd91a4094b868010
2020-07-31T13:46:58.719Z engine stdout {
  timestamp: 'Jul 31 19:16:58.719',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'SELECT "public"."Work"."id", "public"."Work"."userId", "public"."Work"."workType" FROM "public"."Work" WHERE 1=1 OFFSET $1',
    item_type: 'query',
    params: '[0]',
    duration_ms: 4
  }
}
prisma:query SELECT "public"."Work"."id", "public"."Work"."userId", "public"."Work"."workType" FROM "public"."Work" WHERE 1=1 OFFSET $1
2020-07-31T13:46:58.724Z engine {
  error: PrismaClientUnknownRequestError: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s1\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(505), routine: Some("FetchPreparedStatement") }) }) })
      at NodeEngine.graphQLToJSError (/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client/runtime/index.js:1:130234)
      at /Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client/runtime/index.js:1:129120
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async PrismaClientFetcher._request (/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client/runtime/index.js:1:210840)
      at async run (/Users/divyendusingh/Documents/prisma/triage/prisma-2921/index.js:15:14)
}
2020-07-31T13:46:58.726Z engine Stopping Prisma engine
(node:2224) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.work.findMany()` invocation in
/Users/divyendusingh/Documents/prisma/triage/prisma-2921/index.js:15:32


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s1\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(505), routine: Some("FetchPreparedStatement") }) }) })
    at PrismaClientFetcher._request (/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client/runtime/index.js:1:211513)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by divyenduz** [comment]
Note that we still have the original logs from the other day (I happened to have a link to a diff where I was comparing some results https://www.diffchecker.com/Vy2g8fcu)

But since this is not reproducibly anymore, I will keep this closed. 

```
2020-07-02T11:33:45.533Z prisma-client {
  engineConfig: {
    cwd: '/Users/divyendusingh/Downloads/repro 2/prisma',
    enableDebugLogs: false,
    enableEngineDebugMode: undefined,
    datamodelPath: '/Users/divyendusingh/Downloads/repro 2/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/Users/divyendusingh/Downloads/repro 2/node_modules/@prisma/client',
      binaryTargets: [],
      experimentalFeatures: [],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: true,
    flags: [],
    clientVersion: '2.1.3',
    enableExperimental: []
  }
}
2020-07-02T11:33:45.538Z prisma-client Prisma Client call:
2020-07-02T11:33:45.539Z prisma-client prisma.supplier.findMany(undefined)
2020-07-02T11:33:45.539Z prisma-client Generated request:
2020-07-02T11:33:45.539Z prisma-client query {
  findManySupplier {
    accountNumber
    associatedDataImport
    company
    createdAt
    defaultVatRate
    email
    id
    legalName
    paymentTerms
    sortCode
    updatedAt
  }
}

2020-07-02T11:33:45.542Z engine port: 58053
2020-07-02T11:33:45.542Z engine { cwd: '/Users/divyendusingh/Downloads/repro 2/prisma' }
2020-07-02T11:33:45.543Z engine {
  dotPrismaPath: '/Users/divyendusingh/Downloads/repro 2/node_modules/.prisma/client/query-engine-darwin'
}
2020-07-02T11:33:45.544Z plusX Execution permissions of /Users/divyendusingh/Downloads/repro 2/node_modules/.prisma/client/query-engine-darwin are fine
2020-07-02T11:33:45.544Z engine { flags: [ '--enable-raw-queries' ] }
2020-07-02T11:33:45.568Z engine stderr Printing to stderr for debugging
2020-07-02T11:33:45.568Z engine stderr Listening on 127.0.0.1:58053
2020-07-02T11:33:45.580Z engine stdout {
  timestamp: 'Jul 02 17:03:45.579',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a postgresql pool with up to 13 connections.' }
}
2020-07-02T11:33:45.597Z engine stdout {
  timestamp: 'Jul 02 17:03:45.597',
  level: 'INFO',
  target: 'query_engine::server',
  fields: { message: 'Started http server on 127.0.0.1:58053' }
}
2020-07-02T11:33:45.598Z prisma-client Client Version 2.1.3
2020-07-02T11:33:45.598Z prisma-client Engine Version 363f5a521d6b06543e53d134652a0037a3096d41
2020-07-02T11:33:45.695Z engine stdout {
  timestamp: 'Jul 02 17:03:45.695',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: { query: 'BEGIN', item_type: 'query', params: '[]', duration_ms: 8 }
}
prisma:query BEGIN
2020-07-02T11:33:45.700Z engine stdout {
  timestamp: 'Jul 02 17:03:45.700',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'DEALLOCATE ALL',
    item_type: 'query',
    params: '[]',
    duration_ms: 5
  }
}
prisma:query DEALLOCATE ALL
2020-07-02T11:33:45.754Z engine stdout {
  timestamp: 'Jul 02 17:03:45.754',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'SELECT "zebra2"."Supplier"."id", "zebra2"."Supplier"."accountNumber", "zebra2"."Supplier"."associatedDataImport", "zebra2"."Supplier"."company", "zebra2"."Supplier"."createdAt", "zebra2"."Supplier"."defaultVatRate", "zebra2"."Supplier"."email", "zebra2"."Supplier"."legalName", "zebra2"."Supplier"."paymentTerms", "zebra2"."Supplier"."sortCode", "zebra2"."Supplier"."updatedAt" FROM "zebra2"."Supplier" WHERE 1=1 OFFSET $1',
    item_type: 'query',
    params: '[0]',
    duration_ms: 53
  }
}
prisma:query SELECT "zebra2"."Supplier"."id", "zebra2"."Supplier"."accountNumber", "zebra2"."Supplier"."associatedDataImport", "zebra2"."Supplier"."company", "zebra2"."Supplier"."createdAt", "zebra2"."Supplier"."defaultVatRate", "zebra2"."Supplier"."email", "zebra2"."Supplier"."legalName", "zebra2"."Supplier"."paymentTerms", "zebra2"."Supplier"."sortCode", "zebra2"."Supplier"."updatedAt" FROM "zebra2"."Supplier" WHERE 1=1 OFFSET $1
2020-07-02T11:33:45.763Z engine stdout {
  timestamp: 'Jul 02 17:03:45.763',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: { query: 'COMMIT', item_type: 'query', params: '[]', duration_ms: 9 }
}
prisma:query COMMIT
2020-07-02T11:33:45.767Z prisma-client Prisma Client call:
2020-07-02T11:33:45.767Z prisma-client prisma.supplierInvoice.findMany(undefined)
2020-07-02T11:33:45.767Z prisma-client Generated request:
2020-07-02T11:33:45.767Z prisma-client query {
  findManySupplierInvoice {
    associatedDataImport
    company
    createdAt
    currency
    dueDate
    id
    isRefund
    linkedSupplier
    reference
    sentDate
    state
    supplierAccountNumber
    supplierEmail
    supplierLegalName
    supplierPaymentTerms
    supplierSortCode
    updatedAt
  }
}

2020-07-02T11:33:45.778Z engine stdout {
  timestamp: 'Jul 02 17:03:45.778',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: { query: 'BEGIN', item_type: 'query', params: '[]', duration_ms: 9 }
}
prisma:query BEGIN
2020-07-02T11:33:45.785Z engine stdout {
  timestamp: 'Jul 02 17:03:45.785',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'DEALLOCATE ALL',
    item_type: 'query',
    params: '[]',
    duration_ms: 6
  }
}
prisma:query DEALLOCATE ALL
2020-07-02T11:33:45.811Z engine stdout {
  timestamp: 'Jul 02 17:03:45.811',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'SELECT "zebra2"."SupplierInvoice"."id", "zebra2"."SupplierInvoice"."associatedDataImport", "zebra2"."SupplierInvoice"."company", "zebra2"."SupplierInvoice"."createdAt", "zebra2"."SupplierInvoice"."currency", "zebra2"."SupplierInvoice"."dueDate", "zebra2"."SupplierInvoice"."isRefund", "zebra2"."SupplierInvoice"."linkedSupplier", "zebra2"."SupplierInvoice"."reference", "zebra2"."SupplierInvoice"."sentDate", "zebra2"."SupplierInvoice"."state", "zebra2"."SupplierInvoice"."supplierAccountNumber", "zebra2"."SupplierInvoice"."supplierEmail", "zebra2"."SupplierInvoice"."supplierLegalName", "zebra2"."SupplierInvoice"."supplierPaymentTerms", "zebra2"."SupplierInvoice"."supplierSortCode", "zebra2"."SupplierInvoice"."updatedAt" FROM "zebra2"."SupplierInvoice" WHERE 1=1 OFFSET $1',
    item_type: 'query',
    params: '[0]',
    duration_ms: 25
  }
}
prisma:query SELECT "zebra2"."SupplierInvoice"."id", "zebra2"."SupplierInvoice"."associatedDataImport", "zebra2"."SupplierInvoice"."company", "zebra2"."SupplierInvoice"."createdAt", "zebra2"."SupplierInvoice"."currency", "zebra2"."SupplierInvoice"."dueDate", "zebra2"."SupplierInvoice"."isRefund", "zebra2"."SupplierInvoice"."linkedSupplier", "zebra2"."SupplierInvoice"."reference", "zebra2"."SupplierInvoice"."sentDate", "zebra2"."SupplierInvoice"."state", "zebra2"."SupplierInvoice"."supplierAccountNumber", "zebra2"."SupplierInvoice"."supplierEmail", "zebra2"."SupplierInvoice"."supplierLegalName", "zebra2"."SupplierInvoice"."supplierPaymentTerms", "zebra2"."SupplierInvoice"."supplierSortCode", "zebra2"."SupplierInvoice"."updatedAt" FROM "zebra2"."SupplierInvoice" WHERE 1=1 OFFSET $1
2020-07-02T11:33:45.818Z engine stdout {
  timestamp: 'Jul 02 17:03:45.818',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'ROLLBACK',
    item_type: 'query',
    params: '[]',
    duration_ms: 7
  }
}
prisma:query ROLLBACK
2020-07-02T11:33:45.820Z engine {
  error: PrismaClientUnknownRequestError: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s1\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(512), routine: Some("FetchPreparedStatement") }) }) })
      at NodeEngine.graphQLToJSError (/Users/divyendusingh/Downloads/repro 2/node_modules/@prisma/client/runtime/index.js:1:111450)
      at /Users/divyendusingh/Downloads/repro 2/node_modules/@prisma/client/runtime/index.js:1:109998
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async PrismaClientFetcher.request (/Users/divyendusingh/Downloads/repro 2/node_modules/@prisma/client/runtime/index.js:1:185199)
      at async run (/Users/divyendusingh/Downloads/repro 2/index.js:11:14)
}
2020-07-02T11:33:45.820Z prisma-client Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s1\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(512), routine: Some("FetchPreparedStatement") }) }) })
    at NodeEngine.graphQLToJSError (/Users/divyendusingh/Downloads/repro 2/node_modules/@prisma/client/runtime/index.js:1:111450)
    at /Users/divyendusingh/Downloads/repro 2/node_modules/@prisma/client/runtime/index.js:1:109998
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PrismaClientFetcher.request (/Users/divyendusingh/Downloads/repro 2/node_modules/@prisma/client/runtime/index.js:1:185199)
    at async run (/Users/divyendusingh/Downloads/repro 2/index.js:11:14)
2020-07-02T11:33:45.822Z engine Stopping Prisma engine
(node:450) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.supplierInvoice.findMany()` invocation in
/Users/divyendusingh/Downloads/repro 2/index.js:11:43


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s1\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(512), routine: Some("FetchPreparedStatement") }) }) })
    at PrismaClientFetcher.request (/Users/divyendusingh/Downloads/repro 2/node_modules/@prisma/client/runtime/index.js:1:185866)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:450) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:450) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by divyenduz** [comment]
Example of the logs that show how the `ROLLBACK` currently looks like 

```
2020-07-31T14:35:17.543Z prisma-client {
  engineConfig: {
    cwd: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921',
    debug: false,
    datamodelPath: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client',
      binaryTargets: [],
      experimentalFeatures: [],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: true,
    flags: [],
    clientVersion: '2.2.0-dev.36',
    enableExperimental: []
  }
}
2020-07-31T14:35:17.548Z prisma-client Prisma Client call:
2020-07-31T14:35:17.548Z prisma-client prisma.work.findMany({})
2020-07-31T14:35:17.548Z prisma-client Generated request:
2020-07-31T14:35:17.548Z prisma-client query {
  findManyWork {
    id
    userId
    workType
  }
}

2020-07-31T14:35:17.550Z engine { cwd: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921' }
2020-07-31T14:35:17.551Z engine {
  dotPrismaPath: '/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/.prisma/client/query-engine-darwin'
}
2020-07-31T14:35:17.551Z plusX Execution permissions of /Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/.prisma/client/query-engine-darwin are fine
2020-07-31T14:35:17.551Z engine { flags: [ '--enable-raw-queries' ] }
2020-07-31T14:35:17.553Z engine port: 61247
2020-07-31T14:35:17.572Z engine stdout {
  timestamp: 'Jul 31 20:05:17.571',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a postgresql pool with up to 13 connections.' }
}
2020-07-31T14:35:17.577Z engine stdout {
  timestamp: 'Jul 31 20:05:17.577',
  level: 'INFO',
  target: 'query_engine::server',
  fields: { message: 'Started http server on 127.0.0.1:61247' }
}
2020-07-31T14:35:17.579Z prisma-client Client Version 2.2.0-dev.36
2020-07-31T14:35:17.579Z prisma-client Engine Version a0b56e4a4bc0dc6216e1cb26bd91a4094b868010
2020-07-31T14:35:17.593Z engine stdout {
  timestamp: 'Jul 31 20:05:17.593',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: { query: 'BEGIN', item_type: 'query', params: '[]', duration_ms: 1 }
}
prisma:query BEGIN
2020-07-31T14:35:17.595Z engine stdout {
  timestamp: 'Jul 31 20:05:17.595',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'DEALLOCATE ALL',
    item_type: 'query',
    params: '[]',
    duration_ms: 1
  }
}
prisma:query DEALLOCATE ALL
2020-07-31T14:35:17.603Z engine stdout {
  timestamp: 'Jul 31 20:05:17.603',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'SELECT "public"."Work"."id", "public"."Work"."userId", "public"."Work"."workType" FROM "public"."Work" WHERE 1=1 OFFSET $1',
    item_type: 'query',
    params: '[0]',
    duration_ms: 8
  }
}
prisma:query SELECT "public"."Work"."id", "public"."Work"."userId", "public"."Work"."workType" FROM "public"."Work" WHERE 1=1 OFFSET $1
2020-07-31T14:35:17.605Z engine stdout {
  timestamp: 'Jul 31 20:05:17.604',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: { query: 'COMMIT', item_type: 'query', params: '[]', duration_ms: 1 }
}
prisma:query COMMIT
{ d1: [] }
2020-07-31T14:35:17.609Z prisma-client Prisma Client call:
2020-07-31T14:35:17.609Z prisma-client prisma.user.findMany({})
2020-07-31T14:35:17.610Z prisma-client Generated request:
2020-07-31T14:35:17.610Z prisma-client query {
  findManyUser {
    id
    userType
  }
}

2020-07-31T14:35:17.612Z engine stdout {
  timestamp: 'Jul 31 20:05:17.611',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: { query: 'BEGIN', item_type: 'query', params: '[]', duration_ms: 1 }
}
prisma:query BEGIN
2020-07-31T14:35:17.613Z engine stdout {
  timestamp: 'Jul 31 20:05:17.613',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'DEALLOCATE ALL',
    item_type: 'query',
    params: '[]',
    duration_ms: 1
  }
}
prisma:query DEALLOCATE ALL
2020-07-31T14:35:17.616Z engine stdout {
  timestamp: 'Jul 31 20:05:17.616',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'SELECT "public"."User"."id", "public"."User"."userType" FROM "public"."User" WHERE 1=1 OFFSET $1',
    item_type: 'query',
    params: '[0]',
    duration_ms: 3
  }
}
prisma:query SELECT "public"."User"."id", "public"."User"."userType" FROM "public"."User" WHERE 1=1 OFFSET $1
2020-07-31T14:35:17.618Z engine stdout {
  timestamp: 'Jul 31 20:05:17.618',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields: {
    query: 'ROLLBACK',
    item_type: 'query',
    params: '[]',
    duration_ms: 1
  }
}
prisma:query ROLLBACK
2020-07-31T14:35:17.620Z engine {
  error: PrismaClientUnknownRequestError: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s1\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(505), routine: Some("FetchPreparedStatement") }) }) })
      at NodeEngine.graphQLToJSError (/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client/runtime/index.js:1:130234)
      at /Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client/runtime/index.js:1:129120
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async PrismaClientFetcher._request (/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client/runtime/index.js:1:210840)
      at async run (/Users/divyendusingh/Documents/prisma/triage/prisma-2921/index.js:12:14)
}
2020-07-31T14:35:17.622Z engine Stopping Prisma engine
(node:7443) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.findMany()` invocation in
/Users/divyendusingh/Documents/prisma/triage/prisma-2921/index.js:12:32


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s1\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(505), routine: Some("FetchPreparedStatement") }) }) })
    at PrismaClientFetcher._request (/Users/divyendusingh/Documents/prisma/triage/prisma-2921/node_modules/@prisma/client/runtime/index.js:1:211513)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by divyenduz** [comment]
Is it possible to log the query that failed and caused a rollback?

**Comment by pimeys** [comment]
The last query, even if causing an error, is always logged in Quaint. Here's an example application I wrote to demonstrate how it works:

```rust
use quaint::{connector::*, single::Quaint};

const DATABASE_URI: &'static str =
    "postgresql://postgres:prisma@localhost:5432/postgres?schema=sql_load_test";

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    env_logger::init();

    let conn = Quaint::new(DATABASE_URI).await?;

    let tx = conn.start_transaction().await?;
    tx.query_raw("SELECT 1", &[]).await?;
    tx.query_raw("SELECT aseas", &[]).await?;
    tx.commit().await?;

    Ok(())
}
```

Now, when running this with:

```bash
> env LOG_QUERIES=1 RUST_LOG=quaint=info cargo run
```

we see the following log output:

```
[2020-08-27T09:25:35Z INFO  quaint::single] Starting a postgresql connection.
[2020-08-27T09:25:35Z INFO  quaint::connector::metrics] query: "BEGIN", params: [] (in 0ms)
[2020-08-27T09:25:35Z INFO  quaint::connector::metrics] query: "SELECT 1", params: [] (in 0ms)
[2020-08-27T09:25:35Z INFO  quaint::connector::metrics] query: "SELECT aseas", params: [] (in 0ms)
Error: Error querying the database: db error: ERROR: column "aseas" does not exist
```

This means, in the logs @divyenduz provided, the last logged query is the one triggering the `ROLLBACK`:

```sql
SELECT "public"."User"."id", "public"."User"."userType" FROM "public"."User" WHERE 1=1 OFSET $1
```

Do we need something more to this?

**Comment by pimeys** [comment]
I'm planning to add a new key to the query log row, marking if the query was successful or threw an error.

```
Aug 27 13:06:56.968  INFO quaint::connector::metrics: query="BEGIN" item_type="query" params=[] duration_ms=0 result="success"
Aug 27 13:06:56.969  INFO quaint::connector::metrics: query="SELECT 1" item_type="query" params=[] duration_ms=0 result="success"
Aug 27 13:06:56.969  INFO quaint::connector::metrics: query="SELECT aseas" item_type="query" params=[] duration_ms=0 result="error"
```

**Comment by andrerpena** [comment]
I'm having a very uninformative error 

```
prisma:query BEGIN
Query: BEGIN
prisma:query INSERT INTO "public"."schema_versions" ("id","display_name","schema") VALUES ($1,$2,$3) RETURNING "public"."schema_versions"."id"
Query: INSERT INTO "public"."schema_versions" ("id","display_name","schema") VALUES ($1,$2,$3) RETURNING "public"."schema_versions"."id"
prisma:query ROLLBACK
Query: ROLLBACK
error
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.schemaVersion.create()` invocation:


  Null constraint violation on the fields: ()
    at cb (/Users/andrepena/git/hyperforms/hyperforms-web/node_modules/@prisma/client/runtime/index.js:35101:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'P2011',
  clientVersion: '2.23.0',
  meta: { constraint: [] }
}

There is no information about what caused the ROLLBACK, and the `Null constraint violation on the fields` error doesn't tell me which fields caused the problem
```

**Comment by janpio** [comment]
Please open an issue in https://github.com/prisma/prisma and include all the information it asks for @andrerpena - we will look at this and hopefully reproduce and later fix.
